# Generated by Django 4.2.2 on 2023-06-20 08:54

from django.db import migrations, models
import file_manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemanager',
            name='file',
            field=models.FileField(upload_to='files/', validators=[file_manager.models.FileManager.file_size]),
        ),
        migrations.AlterField(
            model_name='filemanager',
            name='file_size',
            field=models.CharField(max_length=1000),
        ),
    ]
