# Generated by Django 4.2.2 on 2023-06-20 13:15

from django.db import migrations, models
import file_manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0002_alter_filemanager_file_alter_filemanager_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemanager',
            name='file',
            field=models.FileField(upload_to='files/', validators=[file_manager.models.FileManager.file_size_limit]),
        ),
    ]
